name: notify main release
on:
    push:
        branches:
            - 'main-server'
env:
    REPO: quentinhivanhoe/Zappype
    MIRROR_URL: git@github.com:EpitechPromo2028/B-YEP-400-RUN-4-1-zappy-loic.rabearivelo.git
jobs:
    set_repo_name:
        name: "set repo name"
        runs-on: ubuntu-latest
        outputs:
            repoTrigered: ${{ steps.set_repo.outputs.repo_trigered }}
            repoActual: ${{ steps.set_repo.outputs.repo_actual }}
        steps:
            -   name: "check repo name"
                id: set_repo
                run: |
                    echo "repo_trigered=${{ github.repository }}" >> "$GITHUB_OUTPUT"
                    echo "repo_actual=${{ env.REPO }}" >> "$GITHUB_OUTPUT"
    check_repo:
        needs: set_repo_name
        if: needs.set_repo_name.outputs.repoActual == needs.set_repo_name.outputs.repoTrigered
        runs-on: ubuntu-latest
        steps:
            -   name: "set web hook"
                id: set_web_hook
                run: echo "toto"
    notify-discord:
        name: "notify-discord channel"
        runs-on: ubuntu-latest
        needs: check_repo
        steps:
            -   name: "log main"
                id: log_main
                env:
                    DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_SERVER}}
                uses: Ilshidur/action-discord@master
                with:
                    args: "${{ github.event.commits.message }}"
    push_to_mirror:
        runs-on: ubuntu-latest
        needs: check_repo
        steps:
            -   name: checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   name: mirroring
                uses: pixta-dev/repository-mirroring-action@v1
                with:
                    target_repo_url:
                        ${{ env.MIRROR_URL }}
                    ssh_private_key:
                        ${{ secrets.GIT_SSH_PRIVATE_KEY }}
