name: notify main release

on:
    push:
        branches:
            - main
jobs:
    notify-discord:
        name: "notify-discord channel"
        runs-on: ubuntu-latest
        steps:
            -   name: "push message"
                id: push_message
                env:
                    DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_MAIN }}
                uses: Ilshidur/action-discord@master
                with:
                    args: 'Hello server new released from the main branch'

