name: notify main release
on:
    push:
        branches:
            - 'main*'
env:
    REPO: quentinhivanhoe/Zappype
    MIRROR_URL: git@github.com:EpitechPromo2028/B-YEP-400-RUN-4-1-zappy-loic.rabearivelo.git
jobs:
    set_repo_name:
        name: "set repo name"
        runs-on: ubuntu-latest
        outputs:
            repoTrigered: ${{ steps.set_repo.outputs.repo_trigered }}
            repoActual: ${{ steps.set_repo.outputs.repo_actual }}
        steps:
            -   name: "check repo name"
                id: set_repo
                run: |
                    echo "repo_trigered=${{ github.repository }}" >> "$GITHUB_OUTPUT"
                    echo "repo_actual=${{ env.REPO }}" >> "$GITHUB_OUTPUT"
    check_repo:
        needs: set_repo_name
        if: needs.set_repo_name.outputs.repoActual == needs.set_repo_name.outputs.repoTrigered
        runs-on: ubuntu-latest
        env:
            MAIN: "main"
            SERVER: "main-server"
            CLIENT: "main-client"
            IA: "main-ia"
        outputs:
            webHook: ${{ steps.set_web_hook.outputs.web_hook }}
        steps:
            -   name: "set web hook"
                id: set_web_hook
                run: |
                    echo ${{ github.ref_name }}
                    if [ ${{ github.ref_name }} == ${{ env.MAIN }} ]; then
                        echo "web_hook=${{ secrets.WEBHOOK_MAIN }}" >> "$GITHUB_OUTPUT"
                    elif [ ${{ github.ref_name}} == ${{ env.SERVER }} ]; then
                        echo "web_hook=${{ secrets.WEBHOOK_SERVER}}" >> "$GITHUB_OUTPUT"
                    elif [ ${{ github.ref_name}} == ${{ env.CLIENT}} ]; then
                        echo "web_hook=${{ secrets.WEBHOOK_CLIENT}}" >> "$GITHUB_OUTPUT"
                    else
                        echo "web_hook=${{ secrets.WEBHOOK_IA }}" >> "$GITHUB_OUTPUT"
                    fi
    notify-discord:
        name: "notify-discord channel"
        runs-on: ubuntu-latest
        needs: check_repo
        steps:
            -   name: "push message"
                id: push_message
                env:
                    DISCORD_WEBHOOK: ${{ needs.check_repo.outputs.webHook }}
                uses: Ilshidur/action-discord@master
                with:
                    args: "${{ github.event.commits.message }}"
    push_to_mirror:
        runs-on: ubuntu-latest
        needs: check_repo
        steps:
            -   name: checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   name: mirroring
                uses: pixta-dev/repository-mirroring-action@v1
                with:
                    target_repo_url:
                        ${{ env.MIRROR_URL }}
                    ssh_private_key:
                        ${{ secrets.GIT_SSH_PRIVATE_KEY }}

