name: notify for new opened
on:
    issues:
        types: [opened, edited, deleted]
env:
    REPO: quentinhivanhoe/Zappype
jobs:
    set_repo_name:
        name: "set repo name"
        runs-on: ubuntu-latest
        outputs:
            repoTrigered: ${{ steps.set_repo.outputs.repo_trigered }}
            repoActual: ${{ steps.set_repo.outputs.repo_actual }}
        steps:
            -   name: "check repo name"
                id: set_repo
                run: |
                    echo "repo_trigered=${{ github.repository }}" >> "$GITHUB_OUTPUT"
                    echo "repo_actual=${{ env.REPO }}" >> "$GITHUB_OUTPUT"
    check_repo:
        needs: set_repo_name
        if: needs.set_repo_name.outputs.repoActual == needs.set_repo_name.outputs.repoTrigered
        runs-on: ubuntu-latest
        steps:
            -   name: "set web hook"
                id: set_web_hook
                run: echo "toto"
    issue_opened:
        needs: check_repo
        runs-on: ubuntu-latest
        steps:
            -   name: "notify server"
                id: notify_server
                if: contains(github.event.issue, 'server')
                env:
                    ISSUE_ID: ${{ github.event.issue.id }}
                    # ISSUE_ASSIGNEES: ${{ github.event.issue.assignee }}
                    ISSUE_TITLE: ${{ github.event.issue.title}}
                    ISSUE_BODY: ${{ github.event.issue.body }}
                    DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_SERVER}}
                uses: Ilshidur/action-discord@master
                with:
                    args: "issue opened(${{ env.ISSUE_ID}}): ${{ env.ISSUE_TITLE }}\n${{ env.ISSUE_BODY }}"